version: '3.4'

services:
  exampleuseazureblobstorage:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
    - azureblob
   
  azureblob:
    volumes:
    - ./.containers/blob_storage/data:/data 
    ports:
    - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"


